### ISSUE TITLE
HA 5 minute startup time with integration enabled and mug doesn't reconnect

### ISSUE THREAD

**Issue by mclever** [sopelj/hass-ember-mug-component#5] opened 2022-04-09 21:05 UTC
Logs get flooded with this loop and HA takes really long to start up. I don't reboot HA that often, just noticed this after updating to the 2022.4 release to take advantage of some new functionality and while rebooting/testing HA startup takes a really long time with a 5 minute pause in logging entries and then the time out moving forward

ERROR (MainThread) [custom_components.ember_mug] An unexpected error occurred during loop . Restarting.
INFO (MainThread) [custom_components.ember_mug] Starting mug loop

WARNING (MainThread) [homeassistant.bootstrap] Setup timed out for bootstrap - moving forward

**Comment by sopelj** [comment] 2022-04-10 14:42
Hi, that is a long startup time. Is this your total startup time or just the time for this integration? Because normally even if it fails to connect it shouldn't delay the startup of your Home Assistant. You can see the breakdown in the Configuration -> Info tab.

![screenshot-2022-04-10-10-16-38](https://user-images.githubusercontent.com/5285941/162624029-0bfa0a57-b2d8-427c-944f-8a3d27b67142.png)

Yeah, I'm sorry about the logs. I wanted to make sure it was clear what it was doing to facilitate debugging. Maybe I should move the logs to debugging level so it doesn't spam too much.

On the connection front. Have you tried placing your mug in pairing mode and waiting a couple minutes for it to try again?

If that fails too. Maybe try turning bluetooth off and then on again in Home Assistant. In the terminal addon you can do 

```bash
bluetoothctl power off
# wait until it says it's turned off
bluetoothctl power on
```

**Comment by mclever** [comment] 2022-04-10 14:44
I can give that a shot, thanks.

Not as much concerned with the output in the logs, but the 5 minute startup delay because of this thing trying to connect is frustrating.

**Comment by sopelj** [comment] 2022-04-10 14:59
Yes, that would be frustrating. Is it only this integration taking 5min?

**Comment by mclever** [comment] 2022-04-10 15:03
yes, as soon as i disable ember integration and reboot it goes back to normal reboot time without that 

WARNING (MainThread) [homeassistant.bootstrap] Setup timed out for bootstrap - moving forward

**Comment by mclever** [comment] 2022-04-19 00:32
any ideas @sopelj ?

**Comment by sopelj** [comment] 2022-04-19 01:58
@mclever did you try what I suggested earlier? 

I have been having quite a few issues since the latest update as well. It frequently fails to connect, but hasn't affected my startup time. 

The only way I've been able to get Bluetooth working is like I said: turning it off, waiting a few seconds and turning it back on. It doesn't work every time, but finishes by connecting again.

Are you using Home Assistant OS? I am, and there appear to be quite a few Bluetooth related fixes in version 8, so I was hoping that might help get it back to normal. 

I will still see if there's anything I can do to improve it, but even without my integration, the Bluetooth in my installation frequently fails to connect or run commands. It just gives generic errors.

**Comment by mclever** [comment] 2022-04-19 06:24
I couldn't handle the 5 minute delay in startup. I have been making lots of changes lately so I have had your integration disabled.

I am on HASS or whatever its called now, latest GA release, nothing beta. I had serious bluetooth range issues on my pi and have a few ESP32s for some stuff further away from my pi, but my mug being just a few feet away I also had issues.

For stuff further away I have run this https://docs.openmqttgateway.com/ and https://github.com/devWaves/SwitchBot-MQTT-BLE-ESP32

**Comment by mclever** [comment] 2022-04-19 06:33
also, just noticed you don't have an issues link on http://HA IP:port/config/info not sure what that entails, just happened to see when i rebooted with integration enabled and its no longer taking 5 minutes....

![image](https://user-images.githubusercontent.com/60011614/163940393-34d9b761-e44c-4e0d-ae73-606d4dba73b1.png)

**Comment by sopelj** [comment] 2022-10-09 15:49
@mclever Hey, has this continued to happen? Lots has changed in home assistant since this issue. And the latest beta of this package uses the built-in Bluetooth integration, so it shouldn't delay the startup any more. Please let me know if it works for you and if you have issues the cause will be different so I will close this issue, but feel free to open another :)

**Closed by sopelj** 2022-10-09 15:49 UTC

**Comment by mclever** [comment] 2022-10-09 16:57
@sopelj does this work with the built-in BT now? I haven't tried since the BT proxy was a thing as I switched everything over. I will test this week. Thanks

**Comment by sopelj** [comment] 2022-10-09 17:00
> @sopelj does this work with the built-in BT now? I haven't tried since the BT proxy was a thing as I switched everything over. I will test this week. Thanks 

In theory it should as of 2022.10 since they added support for active proxies, but I haven't tested it yet.
