### ISSUE TITLE
Ember mug integration fails to install

### ISSUE THREAD

**Issue by rybackisback** [sopelj/hass-ember-mug-component#48] opened 2024-02-10 01:07 UTC
* Home Assistant Version (2024.2.1):
* Ember Mug Component Version (0.9.1):
* Which device(s) are you using for Bluetooth (Intel NUC built in bluetooth):

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### After I added the HACS Ember integration I tried adding the integration to home assistant and i get the error below

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

### Logs / Errors
Config flow could not be loaded: Unknow error

```
```

**Comment by sopelj** [comment] 2024-02-10 15:47
Hi. Is this a new install or were you upgrading an existing install?
You are on 0.9.1 and not the beta of 1.0.0? Because the config flow hasn't changed in a few versions (although it has again in 1.0.0), so this is a strange error to have on 0.9.1. Have you tried removing the mug and adding it again? There are no more detailed errors in your logs?

**Comment by rybackisback** [comment] 2024-02-10 23:38
I had an old mug that had died which used to work but on a previous version of the integration. So I replaced the mug and have tried reinstalling the integration. Yes its version 0.9.1. Yes have tried reinstalling the hacs integration. Currently i dont have any mugs in my HA to be removed. Its a fresh install. There is nothing else in the logs.

**Comment by sopelj** [comment] 2024-02-11 01:19
OK, that's very weird. I'll try and reproduce. In the meantime, perhaps you can see if the latest beta works for you? I added mine and removed it no problem to test.

**Comment by rybackisback** [comment] 2024-02-11 03:39
I just tried again after updating to 1.0.0-beta-2 and i get the same message.

**Comment by sopelj** [comment] 2024-02-11 16:57
Ok.. That's very strange. What are you doing to get the error? Are you configuring a device that was found automatically or manually trying to add one? The Bluetooth integration is setup or you are using proxies?

**Comment by rybackisback** [comment] 2024-02-11 22:09
After installing the HACS integration and restarting HA I put the mug into pairing mode (after a full reset) and then try to install the integration in HA, this is when i get the error. No the device doesn't get found automatically. Yes the bluetooth integration is installed and it picks up the mac id of the intel nuc built in Bluetooth. No Bluetooth proxies.

**Comment by sopelj** [comment] 2024-02-11 22:16
Hmm, ok. That's not normal that it doesn't find it automatically. It might be caught in an in between state. Could you try removing the device via `bluetoothctl remove your-mac`? It should detect it as soon as it enters pairing mode if it's not already in the list of devices.
If not, please try enabling debug logging and see if you can get a more helpful error message please. Thanks!

**Comment by rybackisback** [comment] 2024-02-11 22:41
Okay ive tried pairing and upairing using pair and remove commands but still get the same error when trying to install the integration. I already have the following enabled in the logger but it does not provide any logs apart from this standard warning: 2024-02-11 13:32:48.143 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration ember_mug which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
#Logger
logger:
  default: error
  logs:
    custom_components.ember_mug: debug
    custom_components.ember_mug.mug: debug
    custom_components.ember_mug.mug.api: debug
    ember_mug: debug
    ember_mug.connection: debug
    ember_mug.mug: debug

**Comment by rybackisback** [comment] 2024-02-11 23:11
Okay i think ive made some progress. when i looked in bluetoothctl devices i could still see my old mug listed. So iused the removed command. I then reinstalled the hacs integration and restarted HA and put the mug into pairing mode, now i get the following when i try to install integration in ha: No new Ember devices were found. Please ensure it is in pairing mode. In the logs i now have this: 
2024-02-12 09:02:19.646 DEBUG (MainThread) [custom_components.ember_mug] Discovered bluetooth device: <habluetooth.models.BluetoothServiceInfoBleak object at 0x7efd40b01d40>

**Comment by sopelj** [comment] 2024-02-11 23:20
Ok, that's very encouraging. So it says it discovered the mug. Do you see it listed as a discovered device? You should be prompted to configure it without having to do anything manually. If you are having issues detecting the mug you can also do `bluetoothctl scan on`.

**Comment by rybackisback** [comment] 2024-02-11 23:51
Okay i tried that and still get the same error: No new Ember devices were found. Please ensure it is in pairing mode.

Could there be remnants of the old ember integration still be present in the homeassistant/components/ folder? I tried but I am am not sure how i can get access to this folder. Earlier when i was trying to remove and reinstall the hacs integration it said you have to remove the integration from ha eventhough there was none.

**Comment by sopelj** [comment] 2024-02-11 23:59
That's so weird. And if you're in bluetoothctl do you see the device show up?
Normally this integration doesn't store anything except a few things in memory. You should never need "reinstall" it. Simply removing your devices entry if it's there:
![image](https://github.com/sopelj/hass-ember-mug-component/assets/5285941/70b7c82b-a44f-415f-9feb-42b11ed77df8)

The other thing is if you have cache issues making sure it's removed from your adapter via `bluetoothctl remove my-mac`. Then simply putting your mug back into pairing mode should automatically make it appear in Home Assistant. No manual intervension should be required on your part except clicking "Check it out" in notifications and then "Configure" on the discovered entry. 

![image](https://github.com/sopelj/hass-ember-mug-component/assets/5285941/90ab06ae-b249-4c15-94f2-3c5ec48a2c2e)
![image](https://github.com/sopelj/hass-ember-mug-component/assets/5285941/6c088c9e-6050-4e39-a27c-29be38da9332)


If your bluetooth adapter is having trouble finding it you can do `bluetoothctl scan on` to make sure it is actively scanning for devices.

**Comment by rybackisback** [comment] 2024-02-12 00:54
Okay the integration failed pop up when i put it on pairing mode. I can see the device bluetoothctl scan on but when i try to install the integration manually with mug in pairing mode i still get No new Ember devices were found. Please ensure it is in pairing mode.

**Comment by sopelj** [comment] 2024-02-12 01:06
Ok, it should pop up. Home Assistant will automatically list it if it is detected and matches the specs. What kind of mug is it? Would it be possible to check what the service uuid is? Perhaps it is different than the ones listed.

**Comment by rybackisback** [comment] 2024-02-12 01:12
Okay the mug is an Ember 295ml Temperature Control Mug 2. How do i go about finding the UUID?

**Comment by sopelj** [comment] 2024-02-12 01:25
Hmm, OK. Should work. You can just do `bluetoothctl info my-mac` It should be the last "Vendor Specific UUID in the list, or you can just copy/screenshot the lot. Thanks!

**Comment by rybackisback** [comment] 2024-02-12 01:32
@sopelj please see below:
![ember](https://github.com/sopelj/hass-ember-mug-component/assets/57133901/189e682b-2c85-491f-afa5-d6b12f346d28)

**Comment by sopelj** [comment] 2024-02-12 01:56
Thanks! I appreciate the information. I hoped it would have been different, but it seems to be the same service UUID as mine and the manufacturer data is there too. It should be detected by Home Assistant and forwarded to this integration.
The only difference I see is mine can see a few more for mine, but there shouldn't be required for detection.
![image](https://github.com/sopelj/hass-ember-mug-component/assets/5285941/4405312b-0fe4-4550-b528-fb546f8971cc)
Is "Passive scanning" checked for your Bluetooth integrationt? I don't think it would have an effect, but might be worth trying with/without.

**Comment by rybackisback** [comment] 2024-02-12 02:15
Okay i tried passive scanning and the trust command and it did not make a difference. still getting the same error: No new Ember devices were found. Please ensure it is in pairing mode.

**Comment by sopelj** [comment] 2024-02-12 02:27
Hmm, ok thanks for trying. I added some extra debug logging to the config flow and created a new beta for 1.0.0 if your up for trying it. It should at least log devices that were found during setup even if they aren't setup.

**Comment by rybackisback** [comment] 2024-02-12 03:29
Okay updated to 1.0.0.-beta 3 and now i see the below in the logs eventhough ive tried to remove and it says its been removed.
2024-02-12 13:26:39.954 DEBUG (MainThread) [custom_components.ember_mug] Skipping device D7:8E:A3:18:D9:92 which is already setup

**Comment by sopelj** [comment] 2024-02-12 03:47
Awesome thanks! That's good progress. If you have an old entity laying around that could explain it all.
Are you sure you don't have an entry in home assistant for it? Do you have anything listed in Settings -> Devices and Services under Ember Mug? ![Screenshot_20240211-224343.png](https://github.com/sopelj/hass-ember-mug-component/assets/5285941/8bd18504-6038-42b7-bb55-a2f086fa6451)

Or under the Entities tab try searching for "ember" and see if anything comes up.

Or maybe an old config in tank or another integration like BLE tracking that uses the address of your mug?

**Comment by rybackisback** [comment] 2024-02-12 04:47
okay success finally!!!

**Comment by sopelj** [comment] 2024-02-12 17:04
Awesome! I'm glad you got it working! Yeah, it being configured but ignored would do it.
I'll close this issue then, but don't hesitate if there is anything else.

**Closed by sopelj** 2024-02-12 17:04 UTC
