### ISSUE TITLE
Ember Cup Compatibility

### ISSUE THREAD

**Issue by C-Sto** [sopelj/hass-ember-mug-component#29] opened 2023-04-11 10:12 UTC
* Home Assistant Version (eg. 2023.2): 2023.4.0
* Ember Mug Component Version (eg. 0.5.0): 0.6.0

### Description

Cup won't pair (maybe not compatible with the component?)
I'm using the Ember Cup (https://ember.com/products/ember-cup), not the mug. 

### What I Did

Set up as per docs. Using an ESP32 BT proxy with ESPHome.
Waited for #15 to be closed
Installed latest versions 

### Logs / Errors

```
2023-04-11 18:07:35.887 DEBUG (MainThread) [ember_mug.mug] New mug connection initialized.
2023-04-11 18:07:35.887 DEBUG (MainThread) [ember_mug.mug] Registered callback: <bound method MugDataUpdateCoordinator._async_handle_callback of <custom_components.ember_mug.coordinator.MugDataUpdateCoordinator object at 0x7f92f11b18a0>>
2023-04-11 18:07:35.887 INFO (MainThread) [custom_components.ember_mug.coordinator] Ember Mug ember-mug-f84b981f1c23 Setup
2023-04-11 18:07:35.887 DEBUG (MainThread) [ember_mug.mug] Registered callback: <function async_setup_entry.<locals>.<lambda> at 0x7f92f120f6d0>
2023-04-11 18:07:35.887 DEBUG (MainThread) [custom_components.ember_mug.coordinator] Bluetooth event. Service Info: <home_assistant_bluetooth.models.BluetoothServiceInfoBleak object at 0x7f92f1037640>, change: BluetoothChange.ADVERTISEMENT
2023-04-11 18:07:35.887 DEBUG (MainThread) [ember_mug.mug] Set new device from F8:4B:98:1F:1C:23: Ember Cup 2 to F8:4B:98:1F:1C:23: Ember Cup 2
2023-04-11 18:07:35.887 DEBUG (MainThread) [ember_mug.mug] Callback <bound method MugDataUpdateCoordinator._async_handle_callback of <custom_components.ember_mug.coordinator.MugDataUpdateCoordinator object at 0x7f92f11b18a0>> already registered
2023-04-11 18:07:35.888 DEBUG (MainThread) [custom_components.ember_mug.coordinator] Updating
2023-04-11 18:07:35.888 DEBUG (MainThread) [ember_mug.mug] Updating the following attributes: {'firmware', 'meta'}
2023-04-11 18:07:35.888 DEBUG (MainThread) [ember_mug.mug] Establishing a new connection from mug (ID: 140269087041104) to F8:4B:98:1F:1C:23: Ember Cup 2
2023-04-11 18:07:35.888 DEBUG (MainThread) [bleak_retry_connector] (F8:4B:98:1F:1C:23) - F8:4B:98:1F:1C:23: Connection attempt: 1
2023-04-11 18:07:35.937 INFO (MainThread) [ember_mug.mug] Subscribe to Push Events
2023-04-11 18:07:36.836 DEBUG (MainThread) [ember_mug.mug] Read attribute 'fc54000c-236c-4c94-8fa9-944a3e5353fa' with value 'bytearray(b'd\x00\x0c\x00b\x00')'
2023-04-11 18:07:37.642 DEBUG (MainThread) [ember_mug.mug] Read attribute 'fc54000d-236c-4c94-8fa9-944a3e5353fa' with value 'bytearray(b'\xf8K\x98\x1f\x1c#SBBG23700704')'
2023-04-11 18:07:37.643 DEBUG (MainThread) [ember_mug.mug] Firing callbacks: {<bound method MugDataUpdateCoordinator._async_handle_callback of <custom_components.ember_mug.coordinator.MugDataUpdateCoordinator object at 0x7f92f11b18a0>>: <function EmberMug.register_callback.<locals>.unregister_callback at 0x7f92f120f760>, <function async_setup_entry.<locals>.<lambda> at 0x7f92f120f6d0>: <function EmberMug.register_callback.<locals>.unregister_callback at 0x7f92f1033640>}
2023-04-11 18:07:37.643 DEBUG (MainThread) [custom_components.ember_mug.coordinator] Callback called in Home Assistant
2023-04-11 18:07:37.643 DEBUG (MainThread) [custom_components.ember_mug] Manually updated ember-mug-f84b981f1c23 data
2023-04-11 18:07:37.643 DEBUG (MainThread) [ember_mug.mug] Attributes updated: [Change(attr='firmware', old_value=None, new_value=MugFirmwareInfo(version=100, hardware=12, bootloader=98)), Change(attr='meta', old_value=None, new_value=MugMeta(mug_id='+EuYHxwj', serial_number='BBG23700704'))]
2023-04-11 18:07:37.643 DEBUG (MainThread) [ember_mug.mug] Updating the following attributes: {'target_temp', 'name', 'led_colour', 'current_temp', 'liquid_level', 'battery', 'temperature_unit', 'liquid_state'}
2023-04-11 18:07:38.053 DEBUG (MainThread) [ember_mug.mug] Read attribute 'fc540003-236c-4c94-8fa9-944a3e5353fa' with value 'bytearray(b'|\x15')'
2023-04-11 18:07:38.056 ERROR (MainThread) [custom_components.ember_mug.coordinator] An error occurred whilst updating the mug: Characteristic fc540001-236c-4c94-8fa9-944a3e5353fa was not found!
```

Happy to provide more details/be provided some direction in terms of debugging etc

**Comment by sopelj** [comment] 2023-04-12 00:19
Hey! Thanks for the logs, very helpful! I had never even heard of the "Ember Cup". It would definitely be good to support it.

Normally, the pairing worked, as it doesn't seem to have logged the warning "Pairing not implemented". But if an error had occurred, it would have been silenced anyway since it fails it run a second time.

I would assume it either, has a different UUID than the Mug or it cannot be named. 
Is there an option to name it in the Ember app like there is with the Mug?

**Comment by C-Sto** [comment] 2023-04-12 00:58
to clarify: 

The personalize tab allows setting the colour. There is a brightness slider, a battery level, and you can set temperature unit/notifications. No option to name it that I can see

**Comment by sopelj** [comment] 2023-04-12 02:24
That's a good question. I know I have  named it from the app before, but I'm not sure how I got the prompt... I was doing a bunch of testing.

What I can do is try and make a build of the integration that allows for the mug name to be optional and also dump all of the characteristics it finds in the logs. Then we can see if there is one for the name. Or at least some extras as most of these are unnamed. See how far it gets.

I can try and do this after work tomorrow or the day after.

**Comment by imhotep** [comment] 2023-04-13 17:49
Hi,
I am having a similar issue with pairing. it tries to connect and then disconnects after 5 seconds.
I do not see an option to rename the device in the app and I do have the ember mug 2. My logs:
```
2023-04-13 10:47:08.716 DEBUG (MainThread) [custom_components.ember_mug] Finished fetching ember-mug-fa15f2995f2b data in 81.016 seconds (success: False)
2023-04-13 10:47:08.717 DEBUG (MainThread) [ember_mug.mug] Unregistered callback: <function async_setup_entry.<locals>.<lambda> at 0x7fa0efce5120>
2023-04-13 10:48:28.805 DEBUG (MainThread) [ember_mug.mug] New mug connection initialized.
2023-04-13 10:48:28.806 DEBUG (MainThread) [ember_mug.mug] Registered callback: <bound method MugDataUpdateCoordinator._async_handle_callback of <custom_components.ember_mug.coordinator.MugDataUpdateCoordinator object at 0x7fa0ec515d20>>
2023-04-13 10:48:28.806 INFO (MainThread) [custom_components.ember_mug.coordinator] Ember Mug ember-mug-fa15f2995f2b Setup
2023-04-13 10:48:28.806 DEBUG (MainThread) [ember_mug.mug] Registered callback: <function async_setup_entry.<locals>.<lambda> at 0x7fa1062c0670>
2023-04-13 10:48:28.806 DEBUG (MainThread) [custom_components.ember_mug.coordinator] Bluetooth event. Service Info: <home_assistant_bluetooth.models.BluetoothServiceInfoBleak object at 0x7fa0f245a0c0>, change: BluetoothChange.ADVERTISEMENT
2023-04-13 10:48:28.806 DEBUG (MainThread) [ember_mug.mug] Set new device from FA:15:F2:99:5F:2B: Ember Ceramic Mug to FA:15:F2:99:5F:2B: Ember Ceramic Mug
2023-04-13 10:48:28.806 DEBUG (MainThread) [ember_mug.mug] Callback <bound method MugDataUpdateCoordinator._async_handle_callback of <custom_components.ember_mug.coordinator.MugDataUpdateCoordinator object at 0x7fa0ec515d20>> already registered
2023-04-13 10:48:28.806 DEBUG (MainThread) [custom_components.ember_mug.coordinator] Updating
2023-04-13 10:48:28.806 DEBUG (MainThread) [ember_mug.mug] Updating the following attributes: {'meta', 'firmware'}
2023-04-13 10:48:28.806 DEBUG (MainThread) [ember_mug.mug] Establishing a new connection from mug (ID: 140329336622384) to FA:15:F2:99:5F:2B: Ember Ceramic Mug
2023-04-13 10:48:28.807 DEBUG (MainThread) [bleak_retry_connector]  (FA:15:F2:99:5F:2B) - FA:15:F2:99:5F:2B: Connection attempt: 1
2023-04-13 10:48:28.807 DEBUG (MainThread) [bleak.backends.bluezdbus.client] Connecting to device @ FA:15:F2:99:5F:2B
2023-04-13 10:48:28.810 DEBUG (MainThread) [bleak.backends.bluezdbus.client] Connecting to BlueZ path /org/bluez/hci0/dev_FA_15_F2_99_5F_2B
2023-04-13 10:48:34.188 DEBUG (MainThread) [bleak.backends.bluezdbus.client] retry due to le-connection-abort-by-local
```

**Comment by sopelj** [comment] 2023-04-14 02:55
@C-Sto I created the 0.6.1 beta 1 which adds a "debug" option which will log the services and characteristics when it connects. So, in order to test, you'd need to:
- Update to the beta
- Remove the cup you've added from your devices in Home Assistant 
- Put it in pairing mode for it to be detected again
- Add it like you did last time, but in the options check off the "Debug" checkbox at the bottom. (If you have no label it is just a cache issue, just check the second checkbox at the bottom)
Then you can check the logs.and you should have the stuff listed under the entry: `DEBUG [utils.py.log_services:53] Logging all services that were discovered`. 
When in doubt, extra logs are always useful.
Sorry if it's complicate. Please let me know if you have issues or questions. :)

**Comment by sopelj** [comment] 2023-04-14 03:04
> Hi, I am having a similar issue with pairing. it tries to connect and then disconnects after 5 seconds. I do not see an option to rename the device in the app and I do have the ember mug

Hi! I can see how it might look similar, but this is specifically about another device the Ember "Cup" which is not the same as the "Mug" which is already supported. Your logs seem to indicate you have the `Ember Ceramic Mug` so it should work and is already supported.
The last line of your log `retry due to le-connection-abort-by-local` indicates connectivity issues. This can be caused by multiple devices fighting over your mug, for example if your phone is still connected to it or interference/low signal. There are some helpful tips on the Home assistant page about the Bluetooth Integration: https://www.home-assistant.io/integrations/bluetooth/#bluetooth-interference-with-other-devices

**Comment by C-Sto** [comment] 2023-04-14 05:48
that was quick!

here is the output:

```
2023-04-14 13:46:55.957 DEBUG (MainThread) [ember_mug.utils] Logging all services that were discovered
2023-04-14 13:46:55.957 DEBUG (MainThread) [ember_mug.utils] Service 'Generic Access Profile' (UUID: 00001800-0000-1000-8000-00805f9b34fb) has the characteristics:
00002a00-0000-1000-8000-00805f9b34fb: Device Name
00002a01-0000-1000-8000-00805f9b34fb: Appearance
00002a04-0000-1000-8000-00805f9b34fb: Peripheral Preferred Connection Parameters
00002aa6-0000-1000-8000-00805f9b34fb: Central Address Resolution
2023-04-14 13:46:55.957 DEBUG (MainThread) [ember_mug.utils] Service 'Generic Attribute Profile' (UUID: 00001801-0000-1000-8000-00805f9b34fb) has the characteristics:
2023-04-14 13:46:55.957 DEBUG (MainThread) [ember_mug.utils] Service 'Nordic Semiconductor ASA' (UUID: 0000fe59-0000-1000-8000-00805f9b34fb) has the characteristics:
8ec90003-f315-4f60-9fb8-838830daea50: Buttonless DFU
2023-04-14 13:46:55.957 DEBUG (MainThread) [ember_mug.utils] Service 'Unknown' (UUID: fc543622-236c-4c94-8fa9-944a3e5353fa) has the characteristics:
fc540014-236c-4c94-8fa9-944a3e5353fa: Unknown
fc540002-236c-4c94-8fa9-944a3e5353fa: Unknown
fc540003-236c-4c94-8fa9-944a3e5353fa: Unknown
fc540004-236c-4c94-8fa9-944a3e5353fa: Unknown
fc540005-236c-4c94-8fa9-944a3e5353fa: Unknown
fc540006-236c-4c94-8fa9-944a3e5353fa: Unknown
fc540007-236c-4c94-8fa9-944a3e5353fa: Unknown
fc540008-236c-4c94-8fa9-944a3e5353fa: Unknown
fc54000a-236c-4c94-8fa9-944a3e5353fa: Unknown
fc54000c-236c-4c94-8fa9-944a3e5353fa: Unknown
fc54000d-236c-4c94-8fa9-944a3e5353fa: Unknown
fc54000e-236c-4c94-8fa9-944a3e5353fa: Unknown
fc54000f-236c-4c94-8fa9-944a3e5353fa: Unknown
fc540010-236c-4c94-8fa9-944a3e5353fa: Unknown
fc540011-236c-4c94-8fa9-944a3e5353fa: Unknown
fc540012-236c-4c94-8fa9-944a3e5353fa: Unknown
fc540013-236c-4c94-8fa9-944a3e5353fa: Unknown
2023-04-14 13:46:56.031 INFO (MainThread) [ember_mug.mug] Subscribe to Push Events
2023-04-14 13:46:57.374 DEBUG (MainThread) [ember_mug.mug] Read attribute 'fc54000d-236c-4c94-8fa9-944a3e5353fa' with value 'bytearray(b'\xf8K\x98\x1f\x1c#SBBG23700704')'
2023-04-14 13:46:57.769 DEBUG (MainThread) [ember_mug.mug] Read attribute 'fc54000c-236c-4c94-8fa9-944a3e5353fa' with value 'bytearray(b'd\x00\x0c\x00b\x00')'
2023-04-14 13:46:57.769 DEBUG (MainThread) [ember_mug.mug] Firing callbacks: {<bound method MugDataUpdateCoordinator._async_handle_callback of <custom_components.ember_mug.coordinator.MugDataUpdateCoordinator object at 0x7f19b931e860>>: <function EmberMug.register_callback.<locals>.unregister_callback at 0x7f19ad2b2e60>, <function async_setup_entry.<locals>.<lambda> at 0x7f19bb2aea70>: <function EmberMug.register_callback.<locals>.unregister_callback at 0x7f19bb2ae170>}
2023-04-14 13:46:57.769 DEBUG (MainThread) [custom_components.ember_mug.coordinator] Callback called in Home Assistant
2023-04-14 13:46:57.769 DEBUG (MainThread) [custom_components.ember_mug] Manually updated ember-mug-f84b981f1c23 data
2023-04-14 13:46:57.769 DEBUG (MainThread) [ember_mug.mug] Attributes updated: [Change(attr='meta', old_value=None, new_value=MugMeta(mug_id='+EuYHxwj', serial_number='BBG23700704')), Change(attr='firmware', old_value=None, new_value=MugFirmwareInfo(version=100, hardware=12, bootloader=98))]
2023-04-14 13:46:57.769 DEBUG (MainThread) [ember_mug.mug] Updating the following attributes: {'liquid_level', 'name', 'battery', 'temperature_unit', 'target_temp', 'current_temp', 'liquid_state', 'led_colour'}
2023-04-14 13:46:58.124 ERROR (SyncWorker_3) [homeassistant.components.bluetooth_tracker.device_tracker] Couldn't discover bluetooth devices: [Errno 19] No such device
2023-04-14 13:46:58.174 DEBUG (MainThread) [ember_mug.mug] Read attribute 'fc540005-236c-4c94-8fa9-944a3e5353fa' with value 'bytearray(b'\x00')'
2023-04-14 13:46:58.174 ERROR (MainThread) [custom_components.ember_mug.coordinator] An error occurred whilst updating the mug: Characteristic fc540001-236c-4c94-8fa9-944a3e5353fa was not found!
2023-04-14 13:46:58.174 DEBUG (MainThread) [custom_components.ember_mug] Finished fetching ember-mug-f84b981f1c23 data in 2.333 seconds (success: False)
2023-04-14 13:46:58.174 DEBUG (MainThread) [ember_mug.mug] Unregistered callback: <function async_setup_entry.<locals>.<lambda> at 0x7f19bb2aea70>
```

**Comment by sopelj** [comment] 2023-04-14 23:45
@C-Sto Wow, you too! Thanks!
So, it does look like the "Cup" does indeed not have the attribute for the name. 
I'll have to modify the integration to not create the "Name" entities for the cup, but a side from that it **should** work mostly the same. Hopefully it won't take too long to make the change.

**Comment by sopelj** [comment] 2023-04-15 15:16
@C-Sto Ok, I have excluded the name entity if the device is recognized as a "Cup" and it should not try to read it. I created a release 0.6.1 beta 2 which should on theory work, but I can't test it. If you could give it a try it would be much appreciated. Thanks

**Comment by C-Sto** [comment] 2023-04-16 00:10
Looks pretty good to me 😎

![7F38E4B3-6362-425A-A5C6-0097AD7BD7E7](https://user-images.githubusercontent.com/7466346/232259341-c30b9535-0310-40d3-8328-925dc704b516.jpeg)

**Comment by sopelj** [comment] 2023-04-16 01:15
That's awesome! Thanks so much for your help!
I'll close this and create the public release. Don't hesitate if you have any other issues or suggestions. :)

**Closed by sopelj** 2023-04-16 01:15 UTC
